package supermarket;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author Mustafa Khaled
 */
public class CreateBill extends javax.swing.JFrame {

    public CreateBill() {
        initComponents();
        billno();
        showdate();
        Fillcombo();
        gettotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        billno_field = new javax.swing.JTextField();
        cust_field = new javax.swing.JTextField();
        pname_field = new javax.swing.JTextField();
        mrp_field = new javax.swing.JTextField();
        Quan_field = new javax.swing.JTextField();
        pid_field = new javax.swing.JComboBox<>();
        disc_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        date_field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_ = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        Print_btn = new javax.swing.JButton();
        total_field = new javax.swing.JTextField();
        add_btn = new javax.swing.JButton();
        rem_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SuperMarket System (Create Bill)");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Bill No");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Customer Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Product ID");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Mrp");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Quantity");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Discount");

        Quan_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Quan_fieldKeyTyped(evt);
            }
        });

        pid_field.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                pid_fieldPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        disc_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                disc_fieldKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("date");

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 255));

        table_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Mrp", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setText("Total");

        Print_btn.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        Print_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mustafa Khaled\\Documents\\NetBeansProjects\\SuperMarket\\icon\\print.png")); // NOI18N
        Print_btn.setText("print");
        Print_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_btnActionPerformed(evt);
            }
        });

        add_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_btn.setForeground(new java.awt.Color(0, 0, 102));
        add_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mustafa Khaled\\Documents\\NetBeansProjects\\SuperMarket\\icon\\07_plus-20.png")); // NOI18N
        add_btn.setText("add");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        rem_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rem_btn.setForeground(new java.awt.Color(0, 0, 102));
        rem_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mustafa Khaled\\Documents\\NetBeansProjects\\SuperMarket\\icon\\del.png")); // NOI18N
        rem_btn.setText("Remove");
        rem_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rem_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pname_field)
                                    .addComponent(pid_field, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(billno_field, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(cust_field)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(60, 60, 60)
                                .addComponent(disc_field, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mrp_field))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Quan_field, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(add_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rem_btn)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(date_field, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Print_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(total_field, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(billno_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total_field, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Print_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cust_field, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pid_field, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mrp_field, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Quan_field, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(disc_field)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_btn)
                            .addComponent(rem_btn))
                        .addGap(0, 96, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//-----------------------------------------my code ----------------------------------------------------------------------------

    public void gettotal() {
        double sum = 0;
        for (int i = 0; i < table_.getRowCount(); i++) {
            sum = sum + Double.parseDouble(table_.getValueAt(i, 4).toString());
        }
        total_field.setText(Double.toString(sum));
    }
    
    //Function from www.stockoverflow.com
    public static String DateFormat = "yyyy-MM-dd";
    public void showdate() {
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat format = new SimpleDateFormat(DateFormat);
        date_field.setText(format.format(cal.getTime()));

    }

    public void billno() {
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;

        try {
            //1 -Get conection to database
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Supermarket", "root", "");
            //2- create a statement
            st = con.createStatement();
            //3-execute sql query
            rs = st.executeQuery("SELECT COUNT(*) FROM `bill");
            while (rs.next()) {
                int g = Integer.parseInt(rs.getString(1));
                billno_field.setText(String.valueOf(g));

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void billupdate() {
        String query = "INSERT INTO `bill` (`bno`, `CName`, `Price`, `Date`) VALUES (" + billno_field.getText() + ",'" + cust_field.getText() + "'," + total_field.getText() + ",'" + date_field.getText() + "');";
        Connection con;
        Statement st;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/supermarket", "root", "");
            st = con.createStatement();
            st.executeUpdate(query);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void Fillcombo() {
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Supermarket", "root", "");
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM `stock");
            while (rs.next()) {
                String id = rs.getString("id");
                pid_field.addItem(id);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        DefaultTableModel model = (DefaultTableModel) table_.getModel();
        String tmp = (String) pid_field.getSelectedItem();
        String s1 = mrp_field.getText();
        String s2 = Quan_field.getText();
        String s3 = disc_field.getText();
        if(s2.isEmpty()){
            s2="0";
            JOptionPane.showMessageDialog(null, "You should input Quantity ");
        }
        if(s3.isEmpty())
            s3="0.0";
        double mrp = Double.parseDouble(s1);
        int quan = Integer.parseInt(s2);
        double disc = (100.0 - (Double.parseDouble(s3))) / 100;
        double price = mrp * quan * disc;
        Connection con = null;
        Statement st1 = null;
        Statement st2 = null;
        ResultSet rs=null;
        String sql1="select * from `stock` Where id ='"+tmp+"'";
        String sql2="UPDATE `stock` SET `available` = `available` -'"+ quan +"' WHERE `id`='"+tmp+"'";
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Supermarket", "root", "");
            st1 = con.createStatement();
            st2 = con.createStatement();
            rs=st1.executeQuery(sql1);
            while(rs.next()){
                String s4=rs.getString(3);
                int ava=Integer.parseInt(s4);
                if(quan>ava){
                    JOptionPane.showMessageDialog(null, "Quantity Can't Exceed Available in stock ( "+ava+" left in stock)");
                }else{
                    st2.executeUpdate(sql2);
                    model.addRow(new Object[]{pid_field.getSelectedItem(), pname_field.getText(), mrp, quan, price});
                }
            }
            gettotal();
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_add_btnActionPerformed

    private void pid_fieldPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_pid_fieldPopupMenuWillBecomeInvisible
        String tmp = (String) pid_field.getSelectedItem();
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        String user = "root";
        String pass = "";

        try {
            //1 -Get conection to database
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Supermarket", user, pass);
            //2- create a statement
            st = con.createStatement();
            //3-execute sql query
            rs = st.executeQuery("SELECT * FROM `stock` WHERE id='" + tmp + "' ");
            if (rs.next()) {;
                String add = rs.getString("pname");
                pname_field.setText(add);
                add = rs.getString("price");
                mrp_field.setText(add);
            }
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(null, exc);
        }

    }//GEN-LAST:event_pid_fieldPopupMenuWillBecomeInvisible

    private void table_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_MouseClicked
        DefaultTableModel model = (DefaultTableModel) table_.getModel();
        pid_field.setSelectedItem(model.getValueAt(table_.getSelectedRow(), 0).toString());
        pname_field.setText(model.getValueAt(table_.getSelectedRow(), 1).toString());
        mrp_field.setText(model.getValueAt(table_.getSelectedRow(), 2).toString());
        Quan_field.setText(model.getValueAt(table_.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_table_MouseClicked

    private void Print_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_btnActionPerformed
        billupdate();
        this.dispose();
    }//GEN-LAST:event_Print_btnActionPerformed

    private void rem_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rem_btnActionPerformed
        DefaultTableModel model = (DefaultTableModel)table_.getModel();
        model.removeRow(table_.getSelectedRow());
        String tmp = (String) pid_field.getSelectedItem();
        Connection con = null;
        Statement st = null;
        int qua=Integer.parseInt(Quan_field.getText());
        String sq="UPDATE `stock` SET `available`=`available` + '"+qua+"' WHERE `id`='"+tmp+"'";
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Supermarket", "root", "");
            st = con.createStatement();
            st.executeUpdate(sq);
            gettotal();
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_rem_btnActionPerformed

    void checkDigit(java.awt.event.KeyEvent evt){
        char a=evt.getKeyChar();
        if(!(Character.isDigit(a)|| (a==KeyEvent.VK_BACK_SPACE)||(a==KeyEvent.VK_DELETE))){
            evt.consume();
            getToolkit().beep();
        }
    }
    
    private void Quan_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Quan_fieldKeyTyped
        checkDigit(evt);
    }//GEN-LAST:event_Quan_fieldKeyTyped

    private void disc_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_disc_fieldKeyTyped
        checkDigit(evt);
    }//GEN-LAST:event_disc_fieldKeyTyped

//---------------------------------------------------------------------------------------------------------------------------------
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Print_btn;
    private javax.swing.JTextField Quan_field;
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField billno_field;
    private javax.swing.JTextField cust_field;
    private javax.swing.JTextField date_field;
    private javax.swing.JTextField disc_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mrp_field;
    private javax.swing.JComboBox<String> pid_field;
    private javax.swing.JTextField pname_field;
    private javax.swing.JButton rem_btn;
    private javax.swing.JTable table_;
    private javax.swing.JTextField total_field;
    // End of variables declaration//GEN-END:variables
}
