package supermarket;

import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.*;

/**
 *
 * @author Mustafa Khaled
 */
public class stock extends javax.swing.JFrame {

    /**
     * Creates new form stock
     */
    DefaultTableModel model ;
    public stock() {
        initComponents();
        fill_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        add_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        filtertxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        delete_btn = new javax.swing.JButton();
        id_lbl = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        mpr_lbl = new javax.swing.JLabel();
        available_lbl = new javax.swing.JLabel();
        id_field = new javax.swing.JTextField();
        ava_field = new javax.swing.JTextField();
        name_field = new javax.swing.JTextField();
        mpr_field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SuperMarket System (Stockl)");

        add_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_btn.setForeground(new java.awt.Color(0, 0, 107));
        add_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mustafa Khaled\\Documents\\NetBeansProjects\\SuperMarket\\icon\\7-32.png")); // NOI18N
        add_btn.setText("Add");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        update_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update_btn.setForeground(new java.awt.Color(0, 0, 107));
        update_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mustafa Khaled\\Documents\\NetBeansProjects\\SuperMarket\\icon\\up.png")); // NOI18N
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        filtertxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtertxtKeyReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mustafa Khaled\\Documents\\NetBeansProjects\\SuperMarket\\icon\\search-32.png")); // NOI18N

        delete_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(0, 0, 107));
        delete_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mustafa Khaled\\Documents\\NetBeansProjects\\SuperMarket\\icon\\del.png")); // NOI18N
        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        id_lbl.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        id_lbl.setText("Id");

        name_lbl.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        name_lbl.setText("Name");

        mpr_lbl.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        mpr_lbl.setText("mpr");

        available_lbl.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        available_lbl.setText("Available");

        ava_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ava_fieldKeyTyped(evt);
            }
        });

        mpr_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mpr_fieldKeyTyped(evt);
            }
        });

        jScrollPane1.setForeground(new java.awt.Color(51, 102, 255));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Available", "Mpr"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Stock");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(id_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(name_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(available_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mpr_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(add_btn)
                                .addGap(18, 18, 18)
                                .addComponent(update_btn)
                                .addGap(18, 18, 18)
                                .addComponent(delete_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filtertxt))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(id_field, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ava_field, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mpr_field, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)))
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(id_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(name_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(available_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mpr_lbl))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ava_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mpr_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(update_btn)
                                .addComponent(delete_btn))
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(filtertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void filter(String query){
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model);
        System.out.println("1 "+tr);
        table.setRowSorter(tr);
        System.out.println("2 "+tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
        System.out.println("3 "+tr);
    }
    
    public  void fill_table(){
        model =(DefaultTableModel) table.getModel();
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Supermarket", "root", "");
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM `stock");
            while (rs.next()) {
                String obj[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
                model.addRow(obj);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    void checkDigit(KeyEvent evt){
        char a=evt.getKeyChar();
        if(!(Character.isDigit(a)|| (a==KeyEvent.VK_BACK_SPACE)||(a==KeyEvent.VK_DELETE))){
            evt.consume();
            getToolkit().beep();
        }
    }
    
    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        model =(DefaultTableModel) table.getModel();
        Connection con = null;
        Statement st = null;
        int ava=Integer.parseInt(ava_field.getText());
        int mpr=Integer.parseInt(mpr_field.getText());
        String sql1="INSERT INTO `stock` VALUES ('"+id_field.getText()+"', '"+name_field.getText()+"', '"+ava+"', '"+mpr+"')";
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Supermarket", "root", "");
            st = con.createStatement();
            st.executeUpdate(sql1);
            model.addRow(new Object[]{id_field.getText(),name_field.getText(),ava_field.getText(),mpr_field.getText()});
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_add_btnActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        model=(DefaultTableModel) table.getModel();
        id_field.setText(model.getValueAt(table.getSelectedRow(), 0).toString());
        name_field.setText(model.getValueAt(table.getSelectedRow(), 1).toString());
        ava_field.setText(model.getValueAt(table.getSelectedRow(), 2).toString());
        mpr_field.setText(model.getValueAt(table.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        model = (DefaultTableModel) table.getModel();
        Connection con = null;
        Statement st = null;
        int ava=Integer.parseInt(ava_field.getText());
        int mpr=Integer.parseInt(mpr_field.getText());
        String sql1="UPDATE `stock` SET `pName` = '"+name_field.getText()+"', `available` = '"+ava+"', `price` = '"+mpr_field.getText()+"' WHERE `stock`.`id` = '"+id_field.getText()+"'";
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Supermarket", "root", "");
            st = con.createStatement();
            st.executeUpdate(sql1);
            model.setValueAt(name_field.getText(),table.getSelectedRow(),1);
            model.setValueAt(ava_field.getText(),table.getSelectedRow(),2);
            model.setValueAt(mpr_field.getText(),table.getSelectedRow(),3);
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_update_btnActionPerformed
 
    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        model = (DefaultTableModel)table.getModel();
        Connection con = null;
        Statement st = null;
        String sql1="DELETE FROM `stock` WHERE `stock`.`id` = '"+id_field.getText()+"'";
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Supermarket", "root", "");
            st = con.createStatement();
            st.executeUpdate(sql1);
            model.removeRow(table.getSelectedRow());
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void filtertxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtertxtKeyReleased
        String query=filtertxt.getText();
        filter(query);
    }//GEN-LAST:event_filtertxtKeyReleased

    private void ava_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ava_fieldKeyTyped
        checkDigit(evt);
    }//GEN-LAST:event_ava_fieldKeyTyped

    private void mpr_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mpr_fieldKeyTyped
        checkDigit(evt);
    }//GEN-LAST:event_mpr_fieldKeyTyped

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField ava_field;
    private javax.swing.JLabel available_lbl;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTextField filtertxt;
    private javax.swing.JTextField id_field;
    private javax.swing.JLabel id_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mpr_field;
    private javax.swing.JLabel mpr_lbl;
    private javax.swing.JTextField name_field;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JTable table;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
